# _config.yml
title: Pennions documentation
description: >- 
  A documentation site built with GitHub Pages and Jekyll.
baseurl: "" # the subpath of your site, e.g. /docs
url: ""     # the base hostname & protocol, e.g. https://example.com

theme: minima

# GitHub Pages uses this by default
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-relative-links

markdown: kramdown

# Ensure relative linking works like GitHub Pages does
relative_links:
  enabled: true
  collections: true

# Include all necessary files/folders
include:
  - _pages
  - _posts
  - assets

# Exclude these from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
